all:
  hosts:
  children:
    routers:
      children:
        cisco_csr:
          vars:
            ansible_user: admin
            ansible_ssh_pass: cisco
            ansible_become_pass: cisco
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            router-1:
              ansible_host: 192.168.2.20
            router-2:
              ansible_host: 192.168.2.21
            router-3:
              ansible_host: 192.168.2.22
    cisco_9k:
      hosts:
        n9kv-4:
          ansible_host: 192.168.2.23
      vars:
        ansible_user: admin
        ansible_ssh_pass: cisco
        ansible_become_pass: cisco
        ansible_network_os: nxos
        ansible_connection: network_cli
        ansible_become_method: enable
